

informeBDTP1.pdf : informeBDTP1.tex
	pdflatex informeBDTP1.tex
	pdflatex informeBDTP1.tex
	rm -f *.aux *.log *.backup *.out *.toc 

clean : 
		rm -f informeBDTP1.pdf *.aux *.log *.backup *.out *.toc 
